apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace "com.example.princess_health"
    compileSdk 34
    defaultConfig {
        applicationId "com.example.princess_health"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}
